- id: '1532979976875'
  alias: Goodnight
  trigger:
  - entity_id: input_boolean.goodnight
    from: 'on'
    platform: state
    to: 'off'
  action:
  - service: scene.turn_on
    entity_id: scene.goodnight
